version: "3.1"

services:
    schema-api:
      command:
        - runserver
        - 0.0.0.0:80
      image: schema-api-dev
      build:
        context: ..
        dockerfile: deployment/dev.Dockerfile
      ports:
        - "8080:80"
      volumes:
        - ../:/schema-api/
